### ISSUE TITLE
every time ive tried this i get the same error

### ISSUE THREAD

**Issue by hebiohime** [tallforasmurf/Sidetone#2]
File "/Users/lostpuppy/Desktop/untitled folder/Sidetone-master/sidetone.py", line 16, in <module>
    from PyQt5.QtCore import (
ImportError: No module named PyQt5.QtCore
any help?

**Comment by tallforasmurf** [comment]
Hate to be obvious, but have you installed [PyQt](https://pypi.python.org/pypi/PyQt5/5.9.2)? It's a dependency of this code.

**Comment by hebiohime** [comment]
yes ive done
`pip3 install PyQt5`

**Comment by tallforasmurf** [comment]
So if you have a one-line file `test.py` that reads

    import PyQt5.QtCore

and you run it from the command line with

    python test.py

(or python3, whichever you are using to start sidetone) ... does it run?

**Comment by hebiohime** [comment]
`losts-MacBook-Air:~ lostpuppy$ cd '/Users/lostpuppy/Desktop/untitled folder/Sidetone-master/' && '/usr/bin/pythonw'  '/Users/lostpuppy/Desktop/untitled folder/Sidetone-master/sidetone copy.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/lostpuppy/Desktop/untitled folder/Sidetone-master/sidetone copy.py", line 1, in <module>
    import PyQt5.QtCore
ImportError: No module named PyQt5.QtCore
losts-MacBook-Air:Sidetone-master lostpuppy$ 
`
same output i just copied deleted the contents and replaced... I don't know how to create a file heh , plz be patient :D

**Comment by tallforasmurf** [comment]
Well, PyQt5 is required by sidetone. You say it is installed, but it seems that no code can load it. You need to fix that. When a one-line script such as I described works, sidetone will probably work.
