### ISSUE TITLE
Sidetone is distorted but input is not

### ISSUE THREAD

**Issue by mccarthyjames** [tallforasmurf/Sidetone#4]
Hi! I gave this a try but the sidetone I get back is distorted whereas the output of the external mic is not. Everything seems to be working aside from that.

MacBook Pro 2019
macOS 10.15.6
Python 3.8.5
PyQt5 5.15.1

**Comment by tallforasmurf** [comment]
No idea. Describe the distortion? Note the comment [here](https://github.com/tallforasmurf/Sidetone/blob/master/sidetone.py#L179).

**Comment by mccarthyjames** [comment]
Thank you for the reply and apologies for the delay.

The sidetone is both slightly distorted but also several octaves higher than the input -- as if I have inhaled helium! I tried adjusting the value you mentioned and it did seem to affect the quality but did not stop the pitch shifting.

**Comment by tallforasmurf** [comment]
OK I executed sidetone.py, first time in a loooong while, and it appeared to work (Mojave, Python 3.8, PyQt5 5.15.0). Certainly no distortion or pitch shift. OTOH, the volume slider and the mute button seemed to have no effect, which puzzles me and makes me wonder if I am testing correctly. I note you are running Catalina and one decimal point higher of PyQt5. I suspect Catalina.

This is a low priority thing for me, but I will try to investigate further as time permits. I had planned to skip Catalina entirely, also I need to get a stand-alone mic for testing.

**Comment by tallforasmurf** [comment]
Sorry, I am at a dead end. See the updated README.
